- hosts: webservers
  vars:
    my_str: 'This is server {{server_name}}!'

  tasks:

    - name: copy index.html
      ansible.builtin.template:
        src: files/index.html.j2
        dest: /usr/share/nginx/html/index.html.j2
      become: yes
