---
# tasks file for usr_cfg
    - name: "Create user accounts"
      user:
        name: "{{ item }}"
        groups: "sudo"
      with_items: "{{ users }}"

    - name: copy GitTemplate
      template:
        src: files/GitTemplate
        dest: /home/{{item}}/.gitconfig
      with_items: "{{ users }}"

    - name: "Add authorized keys"
      authorized_key:
        user: "{{ item }}"
        key: "{{ lookup('file', 'files/id_rsa.pub') }}"
      with_items: "{{ users }}"
